### ISSUE TITLE
Fix major language used in repository

### ISSUE THREAD

**Issue by MexsonFernandes** [MexsonFernandes/Img2VecCosSim-Django-Pytorch#2]
For JS + CSS is marked as heavily used code in repo. So kindly add git files to ignore JS + CSS and look for Python files.

**Comment by Nyckel** [comment]
The percentages are simply statistics. The high proportion of js and css is due to the many frameworks that are present in the "static" folder.
To lower those percentages you can remove unused css and js files

**Comment by osmarpetry** [comment]
What you expect from this issue @MexsonFernandes. Do you want a `.gitignore` to build files?

**Comment by MexsonFernandes** [comment]
Add a .gitattributes for linguist-vendored.

**Comment by ATolkachev** [comment]
Created PR https://github.com/MexsonFernandes/Img2VecCosSim-Django-Pytorch/issues/2

**Comment by MexsonFernandes** [comment]
merged
